### ISSUE TITLE
Selection of bus routes

### ISSUE THREAD

**Issue by DavidS-RTCC** [wmcadigital/wmn-disruption-sign-up#108]
When selecting bus routes - this element took a while. The search hung, but the wheel was spinning, whilst finding the bus number entered into the search.

Also when I entered 81 this bus route couldn't be found. Although the bus route exists.

**Comment by mrmjprice** [comment]
Hi @DavidS-RTCC 

I've had a look and got 81, so it's an API speed issue.

<img width="798" alt="Screenshot 2020-10-27 at 15 17 01" src="https://user-images.githubusercontent.com/10854265/97322206-78a96e80-1867-11eb-8084-6d15ddf8246f.png">

I know that Andrew is concerned about this, so I will raise it with the back-end devs.

Cheers

**Comment by mrmjprice** [comment]
@Rippled - Please can you talk to Paul/Glyn about this?

The API is very slow to wake up when inactive. We need it to be instant, otherwise, people will not use our services.

We should be aiming for less than a second, not 40 seconds.

Cheers

**Comment by mrmjprice** [comment]
This is still very slow.

Could we use the one for timetables as it's much, much faster?

**Comment by daylesalmon** [comment]
This will be fixed today with the release of #219
