### ISSUE TITLE
Table on mobile

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-disruption-sign-up#111]
Please review table on mobile view. Link 'change' should be on the same lines as where possible, e.g. phon number, name. Please see screenshot attached. 
![IMG_3596](https://user-images.githubusercontent.com/57525718/97415101-b3a9b180-18fc-11eb-91f7-df4f7664e14a.PNG)

**Comment by catiarodriguescosta** [comment]
This was the default behaviour defined on the design system:
https://designsystem.wmnetwork.co.uk/components/table/

Do you still want to change it?

**Comment by KaterinaKir** [comment]
Please follow GDS example, where you have header and cell on one line. Like it is shown here. https://responsive-tables.herokuapp.com/tables/transactions

**Comment by mrmjprice** [comment]
I'd argue this GOV example is clearer: https://design-system.service.gov.uk/patterns/check-answers/
