### ISSUE TITLE
Bus services

### ISSUE THREAD

**Issue by Nsmall2020** [wmcadigital/wmn-disruption-sign-up#131]
Services are not in order example number 11

**Comment by KaterinaKir** [comment]
@Nsmall2020 could you please clarify what order would you like to see. Is it alphabetical order when there is a letter next to number 11?

**Comment by Nsmall2020** [comment]
Hi – sorry yes I think it should be alphabetically with the letters next to the service and also the most convenient bus services at the top. As from what I remember, there were a few 11 services which were not in the region?

Regards


Nikita Small
RTCC Customer Information and Communications Officer

Our organisation is working flexibly, so if you’ve received this email ‘out of hours’, whilst it suits me to email now, I do not expect a response or action outside of your working hours.

**Sorry, not all of our telephones are being monitored during the pandemic. If you do not receive a response from your call within 48 hrs, please contact me via email.**

If you are a customer with a physical or mental health disability and require a reasonable adjustment, please visit our website<https://www.wmca.org.uk/policies> for more information.

Direct Dial:
Mobile: 07584 587912
Email: Nikita.Small@tfwm.org.uk
Website: www.tfwm.org.uk

[HANDS FACE SPACE]

[Transport for West Midlands]<https://www.tfwm.org.uk/>[cid:image007.jpg@01D6B699.00971080]<https://www.transporttimes.co.uk/news.php/19th-Annual-National-Transport-Awards-Reward-Innovative-Transport-Projects-across-the-Nation-469/>

National Transport Awards, City-Region Transport Authority of the Year:  2016, 2017 & 2019

Building a healthier, happier, better connected and more prosperous West Midlands
Transport for West Midlands, 16 Summer Lane, Birmingham, B19 3SD

Confidentiality: The information in this email may be confidential, contain personal and/or sensitive information, and/or may be legally privileged.  If an addressing or transmission error has misdirected this email, please notify the author by replying to this email and then deleting the original and your reply.  If you have received this email in error, any disclosure, copying, distribution, or any action taken or omitted to be taken in reliance on the email, may be prohibited and potentially unlawful.  Any views or opinions expressed in this email are those of the sender and do not necessarily reflect the views of West Midlands Combined Authority, unless explicitly stated otherwise.

Find out about WMCA by visiting https://www.wmca.org.uk

[cid:image008.jpg@01D6B699.00971080]Please consider the environment before printing this email.
