### ISSUE TITLE
Sign up & management: Some addresses in autocomplete have postcode cut off

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-disruption-sign-up#238]
When adding a road name, I've noticed that addresses in the dropdown won't show the last 2 letters of the postcode in the autocomplete. If I select an address, the full postcode still isn't shown.

This happens when adding a road disruption during sign-up and in the management dashboard.

![Screenshot 2021-06-28 at 08 55 48](https://user-images.githubusercontent.com/62507489/123600558-b55ea880-d7ee-11eb-974e-acfab58d1fc5.png)

![Screenshot 2021-06-28 at 08 52 35](https://user-images.githubusercontent.com/62507489/123600561-b5f73f00-d7ee-11eb-81d7-e77355d4e174.png)

![Screenshot 2021-06-28 at 08 54 54](https://user-images.githubusercontent.com/62507489/123600550-b4c61200-d7ee-11eb-9d43-ab1b5023fb8f.png)

**Comment by gldgrnt** [comment]
@jkmnch Unfortunately I'm not sure there's much we can do about this... The api itself only gives an approximate postcode for when searching for a specific road / area.
